language: r
cache: packages

before_install:
  - ./inst/sh/install_cwb.sh
  - ./inst/sh/install_treetagger.sh
  - ./inst/sh/install_corenlp.sh

addons:
  apt:
    packages:
    - libglib2.0-dev
    - libssl-dev
    - libcurl4-openssl-dev

r_packages:
  - RUnit
  - devtools
  - plyr
  - tm
  - rcqp
  - covr

r_github_packages:
  - PolMine/polmineR

warnings_are_errors: false

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'library(covr);codecov(token = "d02e1347-6fa5-4be1-97d5-92a7326ee097")'
