language: r
cache: packages

addons:
  apt:
    packages:
    - libglib2.0-dev
    - libssl-dev
    - libcurl4-openssl-dev

install:
  - mkdir /opt/stanford-corenlp
  - cd /opt/stanford-corenlp
  - wget http://nlp.stanford.edu/software/stanford-corenlp-full-2017-06-09.zip
  - unzip stanford-corenlp-full-2017-06-09.zip
  - rm stanford-corenlp-full-2017-06-09.zip
  - cd stanford-corenlp-full-2017-06-09
  - wget http://nlp.stanford.edu/software/stanford-german-corenlp-2017-06-09-models.jar
  - zip -d stanford-german-corenlp-2017-06-09-models.jar StanfordCoreNLP-german.properties
  - mkdir /opt/treetagger
  - cd /opt/treetagger
  - wget http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/tree-tagger-MacOSX-3.2.tar.gz
  - wget http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/tagger-scripts.tar.gz
  - wget http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/install-tagger.sh
  - wget http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/german-par-linux-3.2-utf8.bin.gz
  - wget http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/english-par-linux-3.2-utf8.bin.gz
  - sh install-tagger.sh

r_packages:
  - RUnit
  - devtools
  - plyr
  - tm
  - rcqp
  - covr

r_github_packages:
  - PolMine/polmineR

warnings_are_errors: false

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'library(covr);codecov(token = "d02e1347-6fa5-4be1-97d5-92a7326ee097")'
