#!/bin/sh

# Set these paths appropriately

BIN=/Users/blaette/Lab/github/ctk/inst/exttools/treetagger/bin
CMD=/Users/blaette/Lab/github/ctk/inst/exttools/treetagger/cmd
LIB=/Users/blaette/Lab/github/ctk/inst/exttools/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
