#!/bin/sh

# Set these paths appropriately

BIN=/Users/blaette/Lab/github/ctk/inst/exttools/treetagger/bin
CMD=/Users/blaette/Lab/github/ctk/inst/exttools/treetagger/cmd
LIB=/Users/blaette/Lab/github/ctk/inst/exttools/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/danish-abbreviations-utf8
PARFILE=${LIB}/danish-utf8.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
