#!/bin/sh

# Set these paths appropriately

BIN=/Users/blaette/Lab/github/ctk/inst/exttools/treetagger/bin
CMD=/Users/blaette/Lab/github/ctk/inst/exttools/treetagger/cmd
LIB=/Users/blaette/Lab/github/ctk/inst/exttools/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
