#' ctkPipe class
#' 
#' @slot projectDir a character string
#' @slot remoteDir dir on server
#' @slot subdirs character 
#' @slot summary a data.frame
#' @slot call the calls that have been applied
#' @slot saxonPath path to saxon
#' @slot treetaggerPath path to treetagger
#' @slot cwbRegistry dir of cwb-registry
#' @slot tasks what to do (data.frame)
#' @slot sAttributes a list generated by the method sAttributesList
#' @exportClass ctkPipe
setClass("ctkPipe",
         representation(
           projectDir="character",
           remoteDir="character",
           subdirs="character",
           summary="data.frame",
           call="character",
           saxonPath="character",
           treetaggerPath="character",
           cwbRegistry="character",
           tasks="data.frame",
           sAttributes="list",
           xslFile="character"
         )
)

#' constructor for a ctkPipe object
#' 
#' @param .Object from time to time
#' @param projectDir the directory with the project
#' @return a ctkPipe object
#' @rdname ctkPipe
#' @aliases treetagger treetagger,ctkPipe-method tokenizeSentences
#'   tokenizeSentences,ctkPipe-method xslt xslt,ctkPipe-method cwbImport
#'   cwbImport,ctkPipe-method findReplace
#'   findReplace,ctkPipe-method describeDir describeDir,ctkPipe-method 
#'   sAttributeList
#'   sAttributeList,ctkPipe-method adjustEncoding
#'   adjustEncoding,ctkPipe-method saveProject saveProject,ctkPipe-method 
#'   rsync rsync,ctkPipe-method
#' @export ctkPipe
ctkPipe <- function(projectDir){
  object <- new(
    "ctkPipe",
    projectDir=projectDir,
    call=deparse(match.call()),
    saxonPath="/opt/saxon/saxon9he.jar",
    treetaggerPath="/opt/treetagger"
    )
  subdirs <- list.dirs(projectDir, full.names=FALSE)
  subdirs <- subdirs[which(subdirs != "")]
  object@subdirs <- setNames(as.character(rep(NA, times=length(subdirs))), subdirs)
  if ("CORPUS_REGISTRY" %in% names(Sys.getenv())) object@cwbRegistry <- Sys.getenv("CORPUS_REGISTRY")
  return(object)
}
