#' pipe class
#' 
#' @slot projectDir a character string
#' @slot remoteDir dir on server
#' @slot subdirs character 
#' @slot summary a data.frame
#' @slot call the calls that have been applied
#' @slot saxonPath path to saxon
#' @slot treetaggerPath path to treetagger
#' @slot registry dir of cwb-registry
#' @slot tasks what to do (data.frame)
#' @slot sAttributes a list generated by the method sAttributesList
#' @exportClass pipe
setClass("pipe",
         representation(
           projectDir = "character",
           remoteDir = "character",
           subdirs = "character",
           summary = "data.frame",
           call = "character",
           saxonPath = "character",
           treetaggerPath = "character",
           registry = "character",
           tasks="data.frame",
           sAttributes = "list",
           xslFile = "character"
         )
)

#' constructor for a pipe object
#' 
#' @param .Object from time to time
#' @param projectDir the directory with the project
#' @return a pipe object
#' @rdname pipe
#' @aliases treetagger treetagger,pipe-method tokenizeSentences
#'   tokenizeSentences,pipe-method xslt xslt,pipe-method encode
#'   encode,pipe-method findReplace
#'   findReplace,pipe-method describeDir describeDir,pipe-method 
#'   sAttributeList
#'   sAttributeList,pipe-method adjustEncoding
#'   adjustEncoding,pipe-method saveProject saveProject,pipe-method 
#'   rsync rsync,pipe-method
#' @export pipe
pipe <- function(projectDir){
  object <- new(
    "pipe",
    projectDir = projectDir,
    call = deparse(match.call()),
    saxonPath = "/opt/saxon/saxon9he.jar",
    treetaggerPath = "/opt/treetagger"
    )
  subdirs <- list.dirs(projectDir, full.names=FALSE)
  subdirs <- subdirs[which(subdirs != "")]
  object@subdirs <- setNames(as.character(rep(NA, times=length(subdirs))), subdirs)
  if ("CORPUS_REGISTRY" %in% names(Sys.getenv())) object@registry <- Sys.getenv("CORPUS_REGISTRY")
  return(object)
}
